language: python

python:
- '3.4'

script:
- tox

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtidy-dev
  - sudo apt-get install -y pandoc

install:
- pip install tox

deploy:
  provider: pypi
  user: foxmask
  password:
    secure: SMBRrjUZ2kngOV89YkMyIh8W21CGa+9l6cvlnBXhmmuTt/jlx4sT2HHSzmIFAAsGYkatGj66AVibVsUaqoch2kIH75IOgww38PSgHP4KuqsDIm7xWCcHPSZfXSC3hi89/RwSzFeHCapVXKTW+EKO6FS9hesG6pSMYVTF6WCXnoQ=
  on:
    tags: true
