language: python
python:
- '3.6'
script:
- tox
sudo: false
addons:
  apt:
    packages:
    - libtidy-dev
    - pandoc
    - redis-server
services:
- redis-server
install:
- pip install tox
deploy:
  provider: pypi
  user: foxmask
  password:
    secure: GrdpuGe7/ALgyOKM8AGfZVKD9j2c/33eR0x7aP5UOCoWt1scAP935BQkyS3IQMminxDEUIYYcT7sVnQql+NYup3eebotPrTQPahsoI/jbYvYWkf9U0M0lGRZJFy6y75T8AMz65ywj0tvlZIh4HPPggtwdaDzS76c49XImvL/4L0=
  on:
    tags: true
