language: python

python:
  - '3.4'

env:
  - DJANGO_SETTINGS_MODULE=django_th.test_settings

install:
  - aptitude install libtidy-0.99-0 
  - pip install -r requirements-all.txt
  - pip install coverage

script:
  - coverage run --source='.,th_evernote,th_rss,th_pocket,th_twitter,th_search,th_holidays' manage.py test -v2

deploy:
  provider: pypi
  user: foxmask
  password:
    secure: SMBRrjUZ2kngOV89YkMyIh8W21CGa+9l6cvlnBXhmmuTt/jlx4sT2HHSzmIFAAsGYkatGj66AVibVsUaqoch2kIH75IOgww38PSgHP4KuqsDIm7xWCcHPSZfXSC3hi89/RwSzFeHCapVXKTW+EKO6FS9hesG6pSMYVTF6WCXnoQ=
  on:
    tags: true
    repo: foxmask/django-th
