version: '2'
services:
  redis:
    image: "redis:alpine"
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=django_th.settings_docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
